<a href="https://colab.research.google.com/github/alok1920/Angularjs-learning/blob/master/Deep_Learning_Lesson01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CHUNK 1: Install & Import (Run this first)

In [2]:
import torch
import numpy as np

print("Pytorch version: ", torch.__version__)
print("We are ready to explore tensor!")

Pytorch version:  2.10.0+cpu
We are ready to explore tensor!


# CHUNK 2: Create Your First Tensors

In [3]:
# SCALAR (0D TENSOR) - JUST ONE NUMBER ----
scalar = torch.tensor(42)
print("SCALAR:", scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim) # 0
print("─" * 40)

# VECTOR (1D tensor) - a list of numbers ---
vector = torch.tensor([12, 45, 67, 23, 89])
print("VECTOR:", vector)
print("Shape:", vector.shape) # torch.Size([5]) = 5 numbers
print("Dimensions:", vector.ndim) # 1
print("─" * 40)

# MATRIX (2D tensor) -- a table of numbers ---
matrix = torch.tensor([
[12, 45, 67],
[23, 11, 89],
[45, 67, 12]
])
print("MATRIX:\n", matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim) # 2

SCALAR: tensor(42)
Shape: torch.Size([])
Dimensions: 0
────────────────────────────────────────
VECTOR: tensor([12, 45, 67, 23, 89])
Shape: torch.Size([5])
Dimensions: 1
────────────────────────────────────────
MATRIX:
 tensor([[12, 45, 67],
        [23, 11, 89],
        [45, 67, 12]])
Shape: torch.Size([3, 3])
Dimensions: 2


# CHUNK 3: The SHAPE Concept (Most Important!)

In [4]:
# SHAPE tells you the SIZE of each dimension
# Think of it as: shape = (depth, rows, columns)

# Let's create a FAKE COLOR IMAGE (3D tensor)
fake_image = torch.zeros(3,244,244)
# zeros = fill with 0s for now

print("Fake Image Tensor Shape:", fake_image.shape) #shape = 3,244,244
print("What each number means:")
print(f" → {fake_image.shape[0]} color channels (R, G, B)") # 3
print(f" → {fake_image.shape[1]} pixels tall") # 244
print(f" → {fake_image.shape[2]} pixels wide") # 244
print(f" → Total numbers in this image: {fake_image.shape[0] * fake_image.shape[1] * fake_image.shape[2]:,}") # 150,528

print("\n─── Now a BATCH of 32 images ───")
batch_of_images = torch.zeros(32, 3, 224, 224)
print("Batch Shape:", batch_of_images.shape)
print("What each number means:")
print(f" → {batch_of_images.shape[0]} images in this batch")
print(f" → {batch_of_images.shape[1]} color channels each")
print(f" → {batch_of_images.shape[2]} x {batch_of_images.shape[3]} pixels each")
print(f" → Total numbers:  {32 * 3 * 224 * 224:,}")

Fake Image Tensor Shape: torch.Size([3, 244, 244])
What each number means:
 → 3 color channels (R, G, B)
 → 244 pixels tall
 → 244 pixels wide
 → Total numbers in this image: 178,608

─── Now a BATCH of 32 images ───
Batch Shape: torch.Size([32, 3, 224, 224])
What each number means:
 → 32 images in this batch
 → 3 color channels each
 → 224 x 224 pixels each
 → Total numbers:  4,816,896


# CHUNK 4: NumPy vs PyTorch (Connecting What You Know!)

In [5]:
# You already know NumPy!
# PyTorch tensors are like NumPy arrays BUT
# they can run on GPU and track gradients (for learning)

# NumPy array you already know
numpy_array = np.array([1.0, 2.0, 3.0, 4.0])
print("NumPy array:", numpy_array)
print("NumPy type:", type(numpy_array))

# Converting to PyTorch tensor (super easy!)
pytorch_tensor = torch.from_numpy(numpy_array)
print("\nPyTorch tensor:", pytorch_tensor)
print("PyTorch type:", type(pytorch_tensor))

# They share the same data!
print("\n─── They behave the same way ───")
print("NumPy mean:", numpy_array.mean())
print("PyTorch mean:", pytorch_tensor.mean())

# The BIG difference - PyTorch can go to GPU!
print("\n─── The superpower PyTorch has ───")
print("Can use GPU:", torch.cuda.is_available())
print("(GPU makes training 10-100x faster!)")

NumPy array: [1. 2. 3. 4.]
NumPy type: <class 'numpy.ndarray'>

PyTorch tensor: tensor([1., 2., 3., 4.], dtype=torch.float64)
PyTorch type: <class 'torch.Tensor'>

─── They behave the same way ───
NumPy mean: 2.5
PyTorch mean: tensor(2.5000, dtype=torch.float64)

─── The superpower PyTorch has ───
Can use GPU: False
(GPU makes training 10-100x faster!)


# CHUNK 5: Real Example - Text Becomes Tensor

In [6]:
# How does a sentence become numbers?
# This is the foundation of ALL LLMs (ChatGPT etc)

sentence = "I love AI"
words = sentence.split()
print("Original sentence:", sentence)
print("Split into words:", words)

# Step 1: Build a vocabulary (word → number mapping)
vocabulary = {"I": 0, "love": 1, "AI": 2,
              "hate": 3, "coding": 4}

# Step 2: Convert words to numbers
word_numbers = [vocabulary[word] for word in words]
print("\nWords to numbers:", word_numbers)

# Step 3: Make it a tensor!
text_tensor = torch.tensor(word_numbers)
print("Text as tensor:", text_tensor)
print("Shape:", text_tensor.shape)
print(f"\n'{sentence}' is now just numbers: {text_tensor.tolist()}")
print("THIS is how ChatGPT reads your text!")

Original sentence: I love AI
Split into words: ['I', 'love', 'AI']

Words to numbers: [0, 1, 2]
Text as tensor: tensor([0, 1, 2])
Shape: torch.Size([3])

'I love AI' is now just numbers: [0, 1, 2]
THIS is how ChatGPT reads your text!


# Mini Challenge!

In [12]:
# CHALLENGE 1 (Easy):
# Create a tensor that represents
# a GRAYSCALE image of 28x28 pixels
# (grayscale = only 1 channel)
# Then print its shape and total number of pixels

grayimage = torch.zeros(1, 28, 28)
print("what each number means")
print(f" -> grayscale = only {grayimage.shape[0]} channels")
print(f" -> {grayimage.shape[1]} pixels tall")
print(f" -> {grayimage.shape[2]} pixels wide")
print(f" -> Total numbers in this image: \
{grayimage.shape[0] * grayimage.shape[1] * grayimage.shape[2]:,}")

# CHALLENGE 2 (Medium):
# Create a tensor for a batch of
# 16 grayscale images (28x28 each)
# Print the shape and explain each dimension
print("\n─── CHALLENGE 2: Now a BATCH of 16 images ───")
batch_grayimages = torch.zeros(16, 1, 28, 28)
print("Batch Shape:", batch_grayimages.shape)
print("What each number means:")
print(f" -> {batch_grayimages.shape[0]} images in this batch")
print(f" -> {batch_grayimages.shape[1]} color channels each")
print(f" -> {batch_grayimages.shape[2]}x\
{batch_grayimages.shape[3]} pixels each")
print(f"  -> Total numbers: \
{16 * 1 * 28 * 28:,}")

print("\n─── CHALLENGE 3 (Curious): ───")
# Try this and tell me what you see:
# What does this tell you about how
# you can ACCESS parts of a tensor?
random_tensor = torch.rand(3, 224, 224)
print(random_tensor[0])  # First channel
print(random_tensor[0][0])  # First row of first channel
print(random_tensor[0][0][0])  # First pixel value

what each number means
 -> grayscale = only 1 channels
 -> 28 pixels tall
 -> 28 pixels wide
 -> Total numbers in this image: 784

─── Now a BATCH of 16 images ───
Batch Shape: torch.Size([16, 1, 28, 28])
What each number means:
 -> 16 images in this batch
 -> 1 color channels each
 -> 28x28 pixels each
  -> Total numbers: 12,544

─── CHALLENGE 3 (Curious): ───
tensor([[0.7694, 0.3168, 0.0877,  ..., 0.5892, 0.4257, 0.6443],
        [0.2238, 0.6538, 0.7803,  ..., 0.7760, 0.1892, 0.0229],
        [0.8813, 0.0182, 0.8435,  ..., 0.5958, 0.0271, 0.5186],
        ...,
        [0.8190, 0.9815, 0.5337,  ..., 0.1475, 0.5179, 0.1110],
        [0.8539, 0.9026, 0.6014,  ..., 0.5750, 0.1641, 0.0304],
        [0.2630, 0.5868, 0.2786,  ..., 0.4914, 0.0450, 0.4684]])
tensor([0.7694, 0.3168, 0.0877, 0.9250, 0.3594, 0.7315, 0.4911, 0.4244, 0.1818,
        0.5696, 0.0303, 0.3044, 0.5435, 0.0688, 0.2020, 0.5305, 0.7177, 0.3981,
        0.1209, 0.3026, 0.6249, 0.3691, 0.9089, 0.7487, 0.2266, 0.0649, 0.2943